name: Build

on:
  push:
    branches:
      - master

env:
  IS_CI: 'true'
  time : 'true'
jobs:
  Windows:
    name: Windows
    runs-on: windows-latest
    env:
      NPM_CACHE: '%APPDATA%\npm-cache'
    # needs: CheckCode
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Node Env
        uses: ./.github/actions/setup

      - name: Build src code
        run: |
          git status --porcelain
          npm run pack:win

      # - name: Release package
      #   run: |
      #     npm run publish:win:7z:x64
      #     npm run publish:win:7z:arm64
      #     npm run publish:win:setup:arm64
      #     npm run publish:win:setup:x64
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BT_TOKEN: ${{ secrets.BT_TOKEN }}

      - name: Generate file MD5
        run: |
          echo "下载软件app">> release.txt
          cd build
          Get-FileHash *.exe,*.7z -Algorithm MD5 | Format-List
      - name: 发布到release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "6.0.1"
          body_path: release.txt
          files: ./build/*


